# Generated by Django 4.2.1 on 2023-05-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_total_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='total_budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='total_expense',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='income',
            name='total_expense',
            field=models.FloatField(default=0),
        ),
    ]
