# Generated by Django 4.2.1 on 2023-05-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='total_expense',
        ),
    ]
